[package]
name = "rust-native"
version = "0.1.0"
authors = ["Joel Silva <joelgbsilva@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.8"
noise = "0.6"